
/*********************************************************************
 * Plugin to Extend Sri Plugin functionality to preload links as well
 * generated by script-ext-html-webpack-plugin
 * Issue Ref: 
 * 1. https://github.com/waysact/webpack-subresource-integrity#preloading
 * 2. https://github.com/numical/script-ext-html-webpack-plugin/issues/55
 *********************************************************************/

const EVENT = 'html-webpack-plugin-alter-asset-tags';
class ExtendSriForPreloadLinksPlugin {
    constructor(options = {}) {
        this.options = options;
    }
    apply(compiler) {
        compiler.plugin('compilation', (compilation) => {
            compilation.plugin(EVENT, (pluginArgs, callback) => {
                try {
                    const linkWithoutSri = pluginArgs.head.filter(el => !(el.attributes.rel == "preload" && el.attributes.integrity));
                    const scriptWithSri = pluginArgs.body.filter(el => el.attributes.integrity);

                    linkWithoutSri.map(el => {
                        if(!el.attributes.crossorigin) el.attributes.crossorigin = "anonymous";
                        if(!el.attributes.integrity) {
                            const integrityValue = scriptWithSri.find(el2 => el2.attributes.src == el.attributes.href).attributes;
                            if(integrityValue && integrityValue.integrity) 
                                el.attributes.integrity = integrityValue.integrity;
                        }
                    })
                    callback(null, pluginArgs);
                } catch (err) {
                    callback(err);
                }

            });
        });
    }
}

module.exports = ExtendSriForPreloadLinksPlugin;